In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

In [2]:
#%pip install handcalcs

In [3]:
from handcalcs import *
from handcalcs import render
import handcalcs

def trigger (sig , thresh= None, transition= "rise", marginI = 20):
    arr=[0]
    if thresh is None: 
        thresh = (sig.max()+sig.min())/2
    for i in range(1, len(sig)):
        if transition =="rise":
            if sig[i-1] <thresh and sig[i] >= thresh and i > arr[-1]+marginI:
                arr.append(i)
        elif sig[i-1] >thresh and sig[i] <= thresh and i > arr[-1]+marginI:
            arr.append(i)
    return arr[1:]

In [4]:
# Initialization 
bl= '#1520c0' # blue 
rd= '#C62828' # red
fig_counter=1

In [5]:
# CONFIGURATIONS
#help(handcalcs.set_option)
handcalcs.set_option("latex_block_start", "$")
handcalcs.set_option("latex_block_end", "$")
handcalcs.set_option("math_environment_end", "aligned")
handcalcs.set_option("use_scientific_notation",True)

In [6]:
from figModelv2 import *

<h1 align="center"> Delta DPS-1125AB 1450W Reverse Engineering </h1>

<img src = "figs/une.jpg">

## Overview

**The signaletic plate and the outside view**

In [12]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/IMG_29_211353.jpg" , 
                         caption1="",
                         first_part_path="", width="40%")

In [8]:
fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_29_211336.jpg", 
    caption1="", 
    img2="figs/IMG_29_211345.jpg",
    caption2="", 
    first_part_path="")

**The PCB**

Dimensions : (Thickness ~1.6mm)

In [9]:

fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_29_211443.jpg", 
    caption1="", 
    img2="figs/IMG_29_211452.jpg",
    caption2="", 
    first_part_path="")

## Power supply schematic

Below is the schematic of some principal parts of the power supply. The purpose is to illustrate the main components rather than provide a 100% accurate schematic.

**Block Diagram of the Schematic**

In [13]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/sch1.png" , 
                         caption1="",
                         first_part_path="", width="90%")

**The EMI Inptut filter**

In [14]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/emi.png" , 
                         caption1="",
                         first_part_path="", width="90%")

The emi filter has a active discharge switch. The idea is to put a small circuit; when the grid voltage is applied, the switch is open. When the user removes the plug, the circuit detects the absence of the 50–60 Hz voltage variation and closes the circuit, so the X-capacitors can be discharged. The discharge resistors are optimized to work only when the plug is removed (small resistor size and simpler thermal management).

**The power factor correction (PFC)**

In [15]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/pfc.png" , 
                         caption1="",
                         first_part_path="", width="90%")

The PFC is a classical hard-switching PFC using 3 MOSFETs and 3 electrolytic capacitors.

**The Flyback Auxiliary Circuit**

In [16]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/flyback.png", 
                         caption1="",
                         first_part_path="", width="90%")

The auxiliary power supply is built around the TOP259EG controller.

**The Main Isolated DC-DC**

In [17]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/dcdc.png", 
                         caption1="",
                         first_part_path="", width="90%")

The isolated 400V-12V DC-DC is a phase shifted full bridge (**PSFB**) converter.

* The main transformer is apparently a no gapped core PQ40/30.

* Primary mosfet is infinient mosfet 20N60CFD 650V 20.7A 220mΩ 

* Secondary mosfet is infinient mosfet 034NE7N 75V 100A 3.4mΩ

* The output inductor is composed of 6 parallel wires, 6 turns, plus a small wire with 10 turns to sense the current

## Component analysis 
### The main transformer (DC-DC transformer)

**Overview of the transformer**

In [18]:

fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_29_211607.jpg", 
    caption1="", 
    img2="figs/IMG_30_170659.jpg",
    caption2="", 
    first_part_path="")


fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_30_170712.jpg", 
    caption1="", 
    img2="figs/IMG_30_170705.jpg",
    caption2="", 
    first_part_path="")

In [52]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/airgap.jpg" , 
                         caption1="The transformer apparently has no air gap",
                         first_part_path="", width="30%")

**Dimension of the transformer**

Below the dimensions of PQ40/30, see the [datasheet](https://product.tdk.com/system/files/dam/doc/product/ferrite/ferrite/ferrite-core/data_sheet/80/db/fer/pq_40_30.pdf).

In [22]:
fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/sc1.png" , 
    caption1="", 
    img2="figs/sc2.png",
    caption2="", 
    first_part_path="", 
    width = "60%")

| Datasheet measurement of PQ40/30 (mm)- Nominal| Actual core dimensions (mm) |
|----|----|
| 40.5| 40 |
| 30.3 | 30 |
| 28 | 28.2 and 27.8 |
| 14.9 | 14.9 ad 15 |
| 5 | 5 |

Regarding the dimensions and the shape of the transformer, it appears to be a TDK PQ40/30 core.

**Characterization of the inductance factor (AL)**

A small signal test is used to cacacterize the AL of the core.
* Setup: 
The function generator (50 Ω) powers the primary winding (23 turns). The input voltage and input current are measured

In [26]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/IMG_30_181418.jpg", 
                         caption1="",
                         first_part_path="", width="50%")

* Scope screenshot:

In [25]:

fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="scope/new3.png", 
                         caption1="",
                         first_part_path="", width="50%")

* Result (5 shots): 
	- Measurement

In [27]:
data= [
[67.1, 33.0,20.2 ,-91.75],
[67.25, 33.2,20.2, -91.06],
[67.67, 33.2,20.3, -93.63],
[67.32, 33.0,20.2, -95.06],
[67.49, 33.0,20.3, -92.08]]
cols = ["Freqkhz", "ch2_mA","ch3_v","phase_deg" ]
df= pd.DataFrame(data, columns=cols)
df

   Freqkhz  ch2_mA  ch3_v  phase_deg
0    67.10    33.0   20.2     -91.75
1    67.25    33.2   20.2     -91.06
2    67.67    33.2   20.3     -93.63
3    67.32    33.0   20.2     -95.06
4    67.49    33.0   20.3     -92.08

	- Calculating the inductance using voltage, current and frequency

In [28]:
# z = LW = v/i
# L = v/(i*2*pi*freq)
df["L_uH"]= 1e6*df['ch3_v']/(df['ch2_mA']*df['Freqkhz']*2*np.pi)
df

   Freqkhz  ch2_mA  ch3_v  phase_deg         L_uH
0    67.10    33.0   20.2     -91.75  1451.894436
1    67.25    33.2   20.2     -91.06  1439.929167
2    67.67    33.2   20.3     -93.63  1438.076235
3    67.32    33.0   20.2     -95.06  1447.149683
4    67.49    33.0   20.3     -92.08  1450.650532

	- The average value is:

In [ ]:
Lm = df.L_uH.mean()
N = 23

Lm =round(Lm)

In [33]:
%%render 
Lm # µH

	- The inductance factor

In [34]:
Lm = df.L_uH.mean()
N = 23

Lm =round(Lm)

In [35]:
%%render
A_L= ( Lm*1e3 ) /N**2 # nH/turns 2

From [TDK datasheet of PQ40/30 cores](https://product.tdk.com/system/files/dam/doc/product/ferrite/ferrite/ferrite-core/data_sheet/80/db/fer/pq_40_30.pdf) the closed reference to this inductance factor is N92 or N49 with 3900 nH.

From [Ferroxcube datasheet](https://www.ferroxcube.com/upload/media/product/file/Pr_ds/PQ40_30.pdf), the closed values are 3F4 (2500nH)and 3F36 (3500 nH).

If we assume that this core corresponds to one of these 2 datasheet cores, we can assume that the actual core is a PQ40/30 3F4.

In [44]:
%%render 
A_Lnom=2500 # nH
error = 100* (A_L - A_Lnom)/A_Lnom #\%

**The litz wire**

|                                             |    |
| :------------------------------------------ | :- |
| Number of wires                             |  |
| External diameter (mm), copper + insulation | - |
| Wire diameter (mm)                          | -|
| Total length                                | —  |

In [48]:

fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="IMG_30_173357.jpg", 
                        img2="IMG_31_172646.jpg",
                         caption1="",caption2="",
                         first_part_path="figs/", width="80%")

**Secondary high-current conductors**

In [54]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/IMG_31_105752.jpg" , 
                         caption1="the shape of one of secondary conductor",
                         first_part_path="", width="30%")

The secondary turns are apparently tin-plated copper. When cut, the copper color is visible.

Dimensions: width = , thickness =

The secondary consists of 6 loops. Each pair of loops forms a center-tapped 1:1 secondary, and the three secondaries are connected in parallel for high-current operation.

The winding arrangement is **SS-PP-SS-PP-SS** (see bellow)<br>
This arrangement is known for its effectiveness in reducing leakage inductance.

In [64]:
fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_30_170712.jpg", 
    caption1="SS-PP-SS-PP-SS arrangement", 

    first_part_path="", 
width = "30%")