In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import handcalcs 
from  handcalcs import *

## Small signal carac

In [3]:
data= [
[67.1, 33.0,20.2 ,-91.75],
[67.25, 33.2,20.2, -91.06],
[67.67, 33.2,20.3, -93.63],
[67.32, 33.0,20.2, -95.06],
[67.49, 33.0,20.3, -92.08]]
cols = ["Freqkhz", "ch2_mA","ch3_v","phase_deg" ]
df= pd.DataFrame(data, columns=cols)
df

   Freqkhz  ch2_mA  ch3_v  phase_deg
0    67.10    33.0   20.2     -91.75
1    67.25    33.2   20.2     -91.06
2    67.67    33.2   20.3     -93.63
3    67.32    33.0   20.2     -95.06
4    67.49    33.0   20.3     -92.08

In [4]:
# z = LW = v/i
# L = v/(i*2*pi*freq)
df["L_uH"]= 1e6*df['ch3_v']/(df['ch2_mA']*df['Freqkhz']*2*np.pi)
df

   Freqkhz  ch2_mA  ch3_v  phase_deg         L_uH
0    67.10    33.0   20.2     -91.75  1451.894436
1    67.25    33.2   20.2     -91.06  1439.929167
2    67.67    33.2   20.3     -93.63  1438.076235
3    67.32    33.0   20.2     -95.06  1447.149683
4    67.49    33.0   20.3     -92.08  1450.650532

In [5]:
df.L_uH.mean()

np.float64(1445.5400106079317)

In [6]:
df.L_uH.mean()*0.9

np.float64(1300.9860095471386)

In [7]:
df.L_uH.mean()*0.9/23**2

np.float64(2.4593308309019632)

In [8]:
N= 23
A_L = 1e3*df.L_uH.mean()/(N**2)
A_L

np.float64(2732.5898121132927)

In [9]:
# https://www.ferroxcube.com/upload/media/product/file/Pr_ds/PQ40_30.pdf
# close to 3F36 = 3500
# OR 3f4 = 2500

In [10]:
# https://product.tdk.com/system/files/dam/doc/product/ferrite/ferrite/ferrite-core/data_sheet/80/db/fer/pq_40_30.pdf
# v= 4.44 N f B A
V =400
# Ae = 190.4 mm2
A = 190.4e-6
f= 135e3/2
B = V/(8*N*f*A)
B

0.16914978551807197

# output inductor

In [11]:
# H130061 hija01 core high flux
# 130061 translates to: Outer Diameter = 13.0 mm (rounded), Height = 6.1 mm (rounded).
# Magnetics Inc. Powder Core Catalog
N = 6 # turns
V = 276 # mv
I = 213 # mA
f= 67.36e3 # hz
L_uH= 1e6*V/(I*f*2*np.pi)
AL = 1000*L_uH/N**2
L_uH , AL

(3.061593532429153, 85.0442647896987)

H   130061   A  /  HIJA01
 [1]    [2]   [3]      [4]


 [1] Material (H): This stands for High Flux (50% Nickel, 50% Iron alloy). If you open any competitor catalog (like Magnetics Inc.), they group their data by material first. You must look under the High Flux section.


 [2] Dimensions (130061): As established, this is the physical size. In a Changsung (CSC) catalog, you look for the 130061 page. In a Magnetics Inc. catalog, you look up 58061.


 [3] Permeability Code (A): This is the smoking gun that gives you your $A_L$ value. In the official CSC classification matrix, the letter A assigned to a High Flux core signifies a Permeability ($\mu$) of 125.


 [4] Tracking Code (HIJA01): This is the factory lot/batch number tracking the day, assembly line, and chemical blend sequence. It has zero impact on electrical performance and can be ignored during design.

In [12]:
# datasheet
AL = 72
AL*N**2

2592

In [13]:
# H130061 hija01 core high flux
# 130061 translates to: Outer Diameter = 13.0 mm (rounded), Height = 6.1 mm (rounded).
# Magnetics Inc. Powder Core Catalog
N = 28# turns
V = 6400 # mv
I = 282 # mA
f= 67.16e3 # hz
L_uH= 1e6*V/(I*f*2*np.pi)
AL = 1000*L_uH/N**2
L_uH , AL
# (53.78241627848233, 68.60002076337031)

(53.78241627848233, 68.60002076337031)