In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

In [2]:
#%pip install handcalcs

In [3]:
from handcalcs import *
from handcalcs import render
import handcalcs

def trigger (sig , thresh= None, transition= "rise", marginI = 20):
    arr=[0]
    if thresh is None: 
        thresh = (sig.max()+sig.min())/2
    for i in range(1, len(sig)):
        if transition =="rise":
            if sig[i-1] <thresh and sig[i] >= thresh and i > arr[-1]+marginI:
                arr.append(i)
        elif sig[i-1] >thresh and sig[i] <= thresh and i > arr[-1]+marginI:
            arr.append(i)
    return arr[1:]

In [4]:
# Initialization 
bl= '#1520c0' # blue 
rd= '#C62828' # red
fig_counter=1

In [5]:
# CONFIGURATIONS
#help(handcalcs.set_option)
handcalcs.set_option("latex_block_start", "$")
handcalcs.set_option("latex_block_end", "$")
handcalcs.set_option("math_environment_end", "aligned")
handcalcs.set_option("use_scientific_notation",True)

In [6]:
from figModelv2 import *

<h1 align="center"> Delta DPS-1125AB 1450W Reverse Engineering </h1>

<div align="center">
  <img align="center" src = "figs/une.jpg">  
</div>

## Overview

**The signaletic plate and the outside view**

In [7]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/IMG_29_211353.jpg" , 
                         caption1="",
                         first_part_path="", width="40%")

In [8]:
fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_29_211336.jpg", 
    caption1="", 
    img2="figs/IMG_29_211345.jpg",
    caption2="", 
    first_part_path="")

**The PCB**

Dimensions : 

* Thickness ~1.6mm
* Length ~ 306mm
* max-width ~ 162mm
* middle-width ~ 128mm

In [9]:

fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_29_211443.jpg", 
    caption1="", 
    img2="figs/IMG_29_211452.jpg",
    caption2="", 
    first_part_path="")

## Power supply schematic

Below is the schematic of some principal parts of the power supply. The purpose is to illustrate the main components rather than provide a 100% accurate schematic.

**Block Diagram of the Schematic**

In [10]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/sch1.png" , 
                         caption1="",
                         first_part_path="", width="90%")

**The EMI Inptut filter**

In [11]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/emi.png" , 
                         caption1="",
                         first_part_path="", width="90%")

The emi filter has a active discharge switch. The idea is to put a small circuit; when the grid voltage is applied, the switch is open. When the user removes the plug, the circuit detects the absence of the 50–60 Hz voltage variation and closes the circuit, so the X-capacitors can be discharged. The discharge resistors are optimized to work only when the plug is removed (small resistor size and simpler thermal management).

**The power factor correction (PFC)**

In [12]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/pfc.png" , 
                         caption1="",
                         first_part_path="", width="90%")

The PFC is a classical hard-switching PFC using 3 MOSFETs and 3 electrolytic capacitors.

The controller is apparently CM6502S (marking CM6502SX) see [datasheet](file:///home/pc/Downloads/CM6502S.PDF). The output driver is built around the NPN transistor PB4350.

**The Flyback Auxiliary Circuit**

In [13]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/flyback.png", 
                         caption1="",
                         first_part_path="", width="90%")

The auxiliary power supply is built around the TOP259EG controller.

**The Main Isolated DC-DC**

In [14]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/dcdc.png", 
                         caption1="",
                         first_part_path="", width="90%")

The isolated 400V-12V DC-DC is a phase shifted full bridge (**PSFB**) converter.

* The main transformer is apparently a no gapped core PQ40/30.

* Primary mosfet is infinient mosfet 20N60CFD 650V 20.7A 220mΩ 

* Secondary mosfet is infinient mosfet 034NE7N 75V 100A 3.4mΩ

* The output inductor is composed of 6 parallel wires (D= 1.2mm), 6 turns, plus a small wire with 10 turns(D= 0.8mm) for auxilary -12V output: see below

* The controller is ucc3895dw, and driver is ucc27324

In [15]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/12VN.png" , 
                         caption1="",
                         first_part_path="", width="40%")

## Component analysis 
### The main transformer (DC-DC transformer)

**Overview of the transformer**

In [16]:

fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_29_211607.jpg", 
    caption1="", 
    img2="figs/IMG_30_170659.jpg",
    caption2="", 
    first_part_path="")


fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_30_170712.jpg", 
    caption1="", 
    img2="figs/IMG_30_170705.jpg",
    caption2="", 
    first_part_path="")

In [17]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/airgap.jpg" , 
                         caption1="The transformer apparently has no air gap",
                         first_part_path="", width="30%")

**Dimension of the transformer**

Below the dimensions of PQ40/30, see the [datasheet](https://product.tdk.com/system/files/dam/doc/product/ferrite/ferrite/ferrite-core/data_sheet/80/db/fer/pq_40_30.pdf).

In [18]:
fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/sc1.png" , 
    caption1="", 
    img2="figs/sc2.png",
    caption2="", 
    first_part_path="", 
    width = "60%")

| Datasheet measurement of PQ40/30 (mm)- Nominal| Actual core dimensions (mm) |
|----|----|
| 40.5| 40 |
| 30.3 | 30 |
| 28 | 28.2 and 27.8 |
| 14.9 | 14.9 ad 15 |
| 5 | 5 |

Regarding the dimensions and the shape of the transformer, it appears to be a TDK PQ40/30 core.

**Characterization of the inductance factor (AL)**

A small signal test is used to cacacterize the AL of the core.
* Setup: 
The function generator (50 Ω) powers the primary winding (23 turns). The input voltage and input current are measured

In [19]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/IMG_30_181418.jpg", 
                         caption1="",
                         first_part_path="", width="50%")

* Scope screenshot:

In [20]:

fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="scope/new3.png", 
                         caption1="",
                         first_part_path="", width="50%")

* Result (5 shots): 
	- Measurement

In [21]:
data= [
[67.1, 33.0,20.2 ,-91.75],
[67.25, 33.2,20.2, -91.06],
[67.67, 33.2,20.3, -93.63],
[67.32, 33.0,20.2, -95.06],
[67.49, 33.0,20.3, -92.08]]
cols = ["Freqkhz", "ch2_mA","ch3_v","phase_deg" ]
df= pd.DataFrame(data, columns=cols)
df

   Freqkhz  ch2_mA  ch3_v  phase_deg
0    67.10    33.0   20.2     -91.75
1    67.25    33.2   20.2     -91.06
2    67.67    33.2   20.3     -93.63
3    67.32    33.0   20.2     -95.06
4    67.49    33.0   20.3     -92.08

	- Calculating the inductance using voltage, current and frequency

In [22]:
# z = LW = v/i
# L = v/(i*2*pi*freq)
df["L_uH"]= 1e6*df['ch3_v']/(df['ch2_mA']*df['Freqkhz']*2*np.pi)
df

   Freqkhz  ch2_mA  ch3_v  phase_deg         L_uH
0    67.10    33.0   20.2     -91.75  1451.894436
1    67.25    33.2   20.2     -91.06  1439.929167
2    67.67    33.2   20.3     -93.63  1438.076235
3    67.32    33.0   20.2     -95.06  1447.149683
4    67.49    33.0   20.3     -92.08  1450.650532

	- The average value is:

In [23]:
Lm = df.L_uH.mean()
N = 23

Lm =round(Lm)

In [24]:
%%render 
Lm # µH

	- The inductance factor

In [25]:
Lm = df.L_uH.mean()
N = 23

Lm =round(Lm)

In [26]:
%%render
A_L= ( Lm*1e3 ) /N**2 # nH/turns 2

From [TDK datasheet of PQ40/30 cores](https://product.tdk.com/system/files/dam/doc/product/ferrite/ferrite/ferrite-core/data_sheet/80/db/fer/pq_40_30.pdf) the closed reference to this inductance factor is N92 or N49 with 3900 nH.

From [Ferroxcube datasheet](https://www.ferroxcube.com/upload/media/product/file/Pr_ds/PQ40_30.pdf), the closed values are 3F4 (2500nH)and 3F36 (3500 nH).

If we assume that this core corresponds to one of these 2 datasheet cores, we can assume that the actual core is a PQ40/30 3F4.

In [27]:
%%render 
A_Lnom=2500 # nH
error = 100* (A_L - A_Lnom)/A_Lnom #\%

**The litz wire**

|                                             |    |
| :------------------------------------------ | :- |
| Number of wires                             |  84|
| External diameter (mm), copper + insulation | 1.5mm |
| Wire diameter (mm)                          | 0.1mm|
| Total length                                | 176cm |

In [28]:

fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="IMG_30_173357.jpg", 
                        img2="IMG_31_172646.jpg",
                         caption1="",caption2="",
                         first_part_path="figs/", width="80%")

**Secondary high-current conductors**

In [29]:
fig_counter=  show_figure_pair_with_captions(fig_counter, 
                         img1="figs/IMG_31_105752.jpg" , 
                         caption1="the shape of one of secondary conductor",
                         first_part_path="", width="80%", 
                                            
                                            
                          img2="figs/IMG_29_211630.jpg" , 
                         caption2="The secondary: PCB side",                                           
                                            )

The secondary turns are apparently tin-plated copper. When cut, the copper color is visible.

Dimensions: width =8.5mm , thickness =0.8/0.9mm

The secondary consists of 6 loops. Each pair of loops forms a center-tapped 1:1 secondary, and the three secondaries are connected in parallel for high-current operation.

The winding arrangement is **SS-PP-SS-PP-SS** (see bellow)<br>
This arrangement is known for its effectiveness in reducing leakage inductance.

In [30]:
fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_30_170712.jpg", 
    caption1="SS-PP-SS-PP-SS arrangement", 

    first_part_path="", 
width = "30%")

**Estimating the Peak AC Flux Density ( $B_{\text{peak}}$)**

n a Phase-Shifted Full-Bridge (PSFB), Full-Bridge primary combined with a Center-Tapped secondary:

$$V_{out} = V_{in} \cdot \left(\frac{N_s}{N_p}\right) \cdot D_{eff}$$

Where:

* **$V_{in}$** = Input DC link voltage.
* **$V_{out}$** = Output DC voltage.
* **$N_p$** = Number of turns on the primary winding.
* **$N_s$** = Number of turns on *one half* of the center-tapped secondary winding (since you specified $n:1:1$, your ratio $\frac{N_s}{N_p} = \frac{1}{n}$).
* **$D_{eff}$** = effective duty cycle of the primary switches, maximum **1.0 (100%)**:

$$D_{eff} = \frac{\phi}{\pi} = \frac{\phi^{\circ}}{180^{\circ}}$$



Because your transformer is specified as $n:1:1$, the primary has $n$ turns, and each half of the secondary has $1$ turn.

$\frac{N_s}{N_p} = \frac{1}{n}$ so:

$$V_{out} = \frac{V_{in} \cdot D_{eff}}{n}$$

And

$$D_{eff} = \frac{V_{out} \cdot n}{V_{in}}$$


Real-World Adjustments

To get an accurate calculation for a real circuit:

$$V_{out} = \left(V_{in} \cdot \frac{1}{n} \cdot D_{eff}\right) - V_{drop}$$

* **$V_{drop}$ :** Voltage drop of the secondary synchronous MOSFETs, voltage reduction caused by the dead-time, duty cycle loss from leakage inductance, and other drops in copper wires.

<br> <br> 
* Application using the ideal formula:

In [31]:
%%render 
V_out =  12.2 # V
V_in  = 400 # V
n = 23 # turns
D_eff =  (V_out*n)/V_in

let's add 5% or margin (to cover the voltage drops)

In [32]:
D_eff =D_eff*1.05

In [33]:
%%render 
D_eff

* The formula of $ B_{peak}$

Full Bridge Max Phase Shift ($\phi = 180^{\circ}$, $D_{eff} = 1$)

$$V_{in} = 4 \cdot B_{\text{peak}} \cdot A_e \cdot N_p \cdot f_s$$


so


$$B_{\text{peak}} = \frac{V_{in}}{4 \cdot A_e \cdot N_p \cdot f_s}$$



For Other Phase Shifts ($\phi < 180^{\circ}$)

$$V_{in} = \frac{4 \cdot B_{\text{peak}} \cdot A_e \cdot N_p \cdot f_s}{D_{eff}}$$


so


$$B_{\text{peak}} = \frac{V_{in} \cdot D_{eff}}{4 \cdot A_e \cdot N_p \cdot f_s}$$

In [34]:
%%render 
f_s = 135e3 / 2 # Hz 
#Aemin_mm = 190.4 # mm2 see PQ40/30 datasheet
Aemin_mm = 174.4  # mm2 see PQ40/30 datasheet
Np = 23
Ae_min= Aemin_mm *1e-6 # m2

B_peak = 1e3 * V_in*D_eff/(4*Ae_min*Np*f_s) # mT

From [Ferroxcube datasheet](https://www.ferroxcube.com/upload/media/product/file/Pr_ds/PQ40_30.pdf), Tthe $Bsat_{min}$ of 3F4 is ***330mT*** (@ 100°C & 25kHz)

Assuming our hypothesis and calculation : operating at ~82% of the saturation limit is risky.

### The output inductor (output filter LC)

In [35]:
fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_30_190903.jpg", 
    caption1="The removed inducotr",
    img2="figs/IMG_30_211954.jpg", 
    caption2="The test winding",

    first_part_path="", 
width = "80%")



fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_30_212215.jpg", 
    caption1="",


    first_part_path="", 
width = "40%")

Dimensions: 
* D-ext = 33.3 mm
* D-int = 19.2 mm
* H = 10.8 mm
* Width (D-ext - D-int) = 6.9/7 mm

In [36]:
fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="scope/new4.png", 
    caption1="Small signal characterization (28 turns)",


    first_part_path="", 
width = "60%")

In [37]:
from math import *

In [38]:
%%render 
# H130061 hija01 core high flux
# 130061 translates to: Outer Diameter = 13.0 mm (rounded), Height = 6.1 mm (rounded).
# Magnetics Inc. Powder Core Catalog
N = 28# turns
V = 6400 # mv
I = 282 # mA
f= 67.16e3 # Hz
L_uH= 1e6*V/(I*f*2*pi) # µH
AL = 1000*L_uH/N**2 # nH
# AL = 68.6nH

Regarding the dimesions, the inductance factor,this core is apparently a high-flux core.

The closed core that i found in internet is C058324A2, see the [datasheet](https://www.mag-inc.com/Media/Magnetics/Datasheets/C058324A2.pdf).

### The control board

**The controller**

The controller is ucc3895dw, and driver is ucc27324

In [39]:
fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_30_162702.jpg", 
    caption1="",
    img2="figs/IMG_30_162727.jpg", 
    caption2="",

    first_part_path="", 
width = "100%")

* The CT capacitor (the blue one) marking is 680pF (code 681)
* The RT resistor is 100kΩ (code 1003)
from the controller ucc3895dw [datasheet ](https://www.ti.com/lit/ds/symlink/ucc2895.pdf), the switching frequency formula:

In [40]:
%%render 3 sci_not
CT = 680e-12 # F
RT = 100e3 # Ω

Fosc= 1/(RT*CT)

* $t_{OSC}$ Formula (see ucc3895dw [datasheet ](https://www.ti.com/lit/ds/symlink/ucc2895.pdf), page 14)

$$
t_{OSC} = \frac{5 \times R_T \times C_T}{48} + 120\,\text{ns}
$$

where:

- $C_T$ is in Farads
- $R_T$ is in Ohms
- $t_{OSC}$ is in seconds
- $C_T$ can range from 100 pF to 880 pF

In [41]:
%%render 3 sci_not
t_OSC = (5*RT*CT)/48+120e-9 # s
f_OSC = 1/t_OSC # Hz 
f_sw = f_OSC/2 # Hz 
f_swkHz = 1e-3 * f_sw  # kHz

In [42]:

fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/timdatasheet.png", 
    caption1="datasheet timing",

    caption2="",

    first_part_path="", 
width = "80%")

Below the measurement of CT voltage, we isolate the control board, power it with 12V (Vcc, GND).

Therorical value of $f_{OSC}$ is 138.8kHZ, measurement 135kHz.

In [43]:

fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="scope/new5.png", 
    caption1="CT capacitor voltage",

    caption2="",

    first_part_path="", 
width = "80%")

**The driver insulation transformers**

Since the control board use 2 no isolated drivers ucc27324, so the designer shose to use gate driver transformer to control the mosfets.

In [44]:


fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_30_212700.jpg", 
    caption1="",

    caption2="",

    first_part_path="", 
width = "50%")

**The fans**

In this power supplay we found 2 DELTA fans QUR0812sh DC12V 0.50A

In [45]:


fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_20260602_133441.jpg", 
    caption1="QUR0812sh DC12V 0.50A ",

    caption2="",

    first_part_path="", 
width = "80%")

From this fan [datasheet](https://www.delta-fan.com/Download/Spec/QFR0812SH-AA39.pdf), this fan has a PWM wire to control the speed.

**The inline EMI filter**

For more information, please check the schematics above

In [46]:
fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_30_162702.jpg", 
    caption1="",
    img2="figs/IMG_30_162727.jpg", 
    caption2="",

    first_part_path="", 
width = "100%")

In [47]:
fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_20260602_133505.jpg", 
    caption1="",
    img2="figs/IMG_20260602_133545.jpg", 
    caption2="",

    first_part_path="", 
width = "100%")


fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_20260602_134022.jpg", 
    caption1="",


    first_part_path="", 
width = "50%")

**The housing**

Below some images of the housing, we didn't check if the insulation is a high temperature plastic or normal polymeter

In [48]:
fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_20260602_133449.jpg", 
    caption1="",
    img2="figs/IMG_20260602_133918.jpg", 
    caption2="",

    first_part_path="", 
width = "100%")

In [49]:
fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_20260602_133922.jpg", 
    caption1="",
    img2="figs/IMG_29_211336.jpg", 
    caption2="",

    first_part_path="", 
width = "100%")

**The flyback circuit**

For more information, please check the schematics above.

We didn't turn ON the power supply, after many check we found the the flyback circuit (TOP259EG) is dead, see below:

In [50]:

fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/IMG_30_114042.jpg", 
    caption1="",
    img2="figs/IMG_30_114408.jpg", 
    caption2="",

    first_part_path="", 
width = "100%")

The flyback transfromer dimensions: 

* L x l x H = 34 mm x 28.2 mm x 11.2 mm

It apparently a E28/17/11 core (EE configuration)

In [51]:

fig_counter= show_figure_pair_with_captions(
    fig_counter, 
    img1="figs/trans1.jpg", 
    caption1="Trans marking",
    img2="figs/trans2.jpg", 
    caption2="Overview of the transformer",

    first_part_path="", 
width = "100%")

This power supply use 4 optocoppler (EL816)

The PFC side is powered with an aux of the flyback with a simple regulator LM317T with R1 (2kΩ marking 2001) and R2 (22.1kΩ marking 2212), R2 has a decoupling parallel capacitor, this cofiguration generate 15V to power the controller of the PFC.